package main


const WHITE_KING = 1
const WHITE_QUEEN = 2
const WHITE_ROOK = 3
const WHITE_BISHOP = 4
const WHITE_KNIGHT = 5
const WHITE_PAWN = 6
const BLACK_KING = 9
const BLACK_QUEEN = 10
const BLACK_ROOK = 11
const BLACK_BISHOP = 12
const BLACK_KNIGHT = 13
const BLACK_PAWN = 14

var PIECES = []int{
    WHITE_KING, WHITE_QUEEN, WHITE_ROOK, WHITE_BISHOP, WHITE_KNIGHT, WHITE_PAWN,
    BLACK_KING, BLACK_QUEEN, BLACK_ROOK, BLACK_BISHOP, BLACK_KNIGHT, BLACK_PAWN,
}

const FEN_WHITE_KING = "K"
const FEN_WHITE_QUEEN = "Q"
const FEN_WHITE_ROOK = "R"
const FEN_WHITE_BISHOP = "B"
const FEN_WHITE_KNIGHT = "N"
const FEN_WHITE_PAWN = "P"
const FEN_BLACK_KING = "k"
const FEN_BLACK_QUEEN = "q"
const FEN_BLACK_ROOK = "r"
const FEN_BLACK_BISHOP = "b"
const FEN_BLACK_KNIGHT = "n"
const FEN_BLACK_PAWN = "p"
const FEN_EMPTY = "x"

const HTML_WHITE_KING = "&#9812;"
const HTML_WHITE_QUEEN = "&#9813;"
const HTML_WHITE_ROOK = "&#9814;"
const HTML_WHITE_BISHOP = "&#9815;"
const HTML_WHITE_KNIGHT = "&#9816;"
const HTML_WHITE_PAWN = "" //"&#9817;"
const HTML_BLACK_KING = "&#9818;"
const HTML_BLACK_QUEEN = "&#9819;"
const HTML_BLACK_ROOK = "&#9820;"
const HTML_BLACK_BISHOP = "&#9821;"
const HTML_BLACK_KNIGHT = "&#9822;"
const HTML_BLACK_PAWN = "" //"&#9823;"

// U+2654
const UTF8_WHITE_KING = "♔"
const UTF8_WHITE_QUEEN = "♕"
const UTF8_WHITE_ROOK = "♖"
const UTF8_WHITE_BISHOP = "♗"
const UTF8_WHITE_KNIGHT = "♘"
const UTF8_WHITE_PAWN = "" //"♙"
const UTF8_BLACK_KING = "♚"
const UTF8_BLACK_QUEEN = "♛"
const UTF8_BLACK_ROOK = "♜"
const UTF8_BLACK_BISHOP = "♝"
const UTF8_BLACK_KNIGHT = "♞"
const UTF8_BLACK_PAWN = "" //"♟"


var FEN_TO_PIECE = map[string]int{
    FEN_WHITE_KING: WHITE_KING,
    FEN_WHITE_QUEEN: WHITE_QUEEN,
    FEN_WHITE_ROOK: WHITE_ROOK,
    FEN_WHITE_BISHOP: WHITE_BISHOP,
    FEN_WHITE_KNIGHT: WHITE_KNIGHT,
    FEN_WHITE_PAWN: WHITE_PAWN,
    FEN_BLACK_KING: BLACK_KING,
    FEN_BLACK_QUEEN: BLACK_QUEEN,
    FEN_BLACK_ROOK: BLACK_ROOK,
    FEN_BLACK_BISHOP: BLACK_BISHOP,
    FEN_BLACK_KNIGHT: BLACK_KNIGHT,
    FEN_BLACK_PAWN: BLACK_PAWN,
    FEN_EMPTY: 0,
}

var PIECE_TO_HTML = map[int]string{
    WHITE_KING: HTML_WHITE_KING,
    WHITE_QUEEN: HTML_WHITE_QUEEN,
    WHITE_ROOK: HTML_WHITE_ROOK,
    WHITE_BISHOP: HTML_WHITE_BISHOP,
    WHITE_KNIGHT: HTML_WHITE_KNIGHT,
    WHITE_PAWN: HTML_WHITE_PAWN,
    BLACK_KING: HTML_BLACK_KING,
    BLACK_QUEEN: HTML_BLACK_QUEEN,
    BLACK_ROOK: HTML_BLACK_ROOK,
    BLACK_BISHOP: HTML_BLACK_BISHOP,
    BLACK_KNIGHT: HTML_BLACK_KNIGHT,
    BLACK_PAWN: HTML_BLACK_PAWN,
}

var FEN_TO_HTML = map[string]string{
    FEN_WHITE_KING: HTML_WHITE_KING,
    FEN_WHITE_QUEEN: HTML_WHITE_QUEEN,
    FEN_WHITE_ROOK: HTML_WHITE_ROOK,
    FEN_WHITE_BISHOP: HTML_WHITE_BISHOP,
    FEN_WHITE_KNIGHT: HTML_WHITE_KNIGHT,
    FEN_WHITE_PAWN: HTML_WHITE_PAWN,
    FEN_BLACK_KING: HTML_BLACK_KING,
    FEN_BLACK_QUEEN: HTML_BLACK_QUEEN,
    FEN_BLACK_ROOK: HTML_BLACK_ROOK,
    FEN_BLACK_BISHOP: HTML_BLACK_BISHOP,
    FEN_BLACK_KNIGHT: HTML_BLACK_KNIGHT,
    FEN_BLACK_PAWN: HTML_BLACK_PAWN,
}

var FEN_TO_UTF8 = map[string]string{
    FEN_WHITE_KING: UTF8_WHITE_KING,
    FEN_WHITE_QUEEN: UTF8_WHITE_QUEEN,
    FEN_WHITE_ROOK: UTF8_WHITE_ROOK,
    FEN_WHITE_BISHOP: UTF8_WHITE_BISHOP,
    FEN_WHITE_KNIGHT: UTF8_WHITE_KNIGHT,
    FEN_WHITE_PAWN: UTF8_WHITE_PAWN,
    FEN_BLACK_KING: UTF8_BLACK_KING,
    FEN_BLACK_QUEEN: UTF8_BLACK_QUEEN,
    FEN_BLACK_ROOK: UTF8_BLACK_ROOK,
    FEN_BLACK_BISHOP: UTF8_BLACK_BISHOP,
    FEN_BLACK_KNIGHT: UTF8_BLACK_KNIGHT,
    FEN_BLACK_PAWN: UTF8_BLACK_PAWN,
}

var PIECE_TO_UTF8 = map[int]string{
    WHITE_KING: UTF8_WHITE_KING,
    WHITE_QUEEN: UTF8_WHITE_QUEEN,
    WHITE_ROOK: UTF8_WHITE_ROOK,
    WHITE_BISHOP: UTF8_WHITE_BISHOP,
    WHITE_KNIGHT: UTF8_WHITE_KNIGHT,
    WHITE_PAWN: UTF8_WHITE_PAWN,
    BLACK_KING: UTF8_BLACK_KING,
    BLACK_QUEEN: UTF8_BLACK_QUEEN,
    BLACK_ROOK: UTF8_BLACK_ROOK,
    BLACK_BISHOP: UTF8_BLACK_BISHOP,
    BLACK_KNIGHT: UTF8_BLACK_KNIGHT,
    BLACK_PAWN: UTF8_BLACK_PAWN,
}
